
(function(w,o,undefined){if(o===undefined){return;}
o.scrollIndicatorClassName="overthrow";var doc=w.document,docElem=doc.documentElement,nativeOverflow=o.support==="native",canBeFilledWithPoly=o.canBeFilledWithPoly,configure=o.configure,set=o.set,forget=o.forget,scrollIndicatorClassName=o.scrollIndicatorClassName;o.closest=function(target,ascend){return!ascend&&target.className&&target.className.indexOf(scrollIndicatorClassName)>-1&&target||o.closest(target.parentNode);};var enabled=false;o.set=function(){set();if(enabled||nativeOverflow||!canBeFilledWithPoly){return;}
w.overthrow.addClass();enabled=true;o.support="polyfilled";o.forget=function(){forget();enabled=false;if(doc.removeEventListener){doc.removeEventListener("touchstart",start,false);}};var elem,lastTops=[],lastLefts=[],lastDown,lastRight,resetVertTracking=function(){lastTops=[];lastDown=null;},resetHorTracking=function(){lastLefts=[];lastRight=null;},inputs,setPointers=function(val){inputs=elem.querySelectorAll("textarea, input");for(var i=0,il=inputs.length;i<il;i++){inputs[i].style.pointerEvents=val;}},changeScrollTarget=function(startEvent,ascend){if(doc.createEvent){var newTarget=(!ascend||ascend===undefined)&&elem.parentNode||elem.touchchild||elem,tEnd;if(newTarget!==elem){tEnd=doc.createEvent("HTMLEvents");tEnd.initEvent("touchend",true,true);elem.dispatchEvent(tEnd);newTarget.touchchild=elem;elem=newTarget;newTarget.dispatchEvent(startEvent);}}},start=function(e){if(o.intercept){o.intercept();}
resetVertTracking();resetHorTracking();elem=o.closest(e.target);if(!elem||elem===docElem||e.touches.length>1){return;}
setPointers("none");var touchStartE=e,scrollT=elem.scrollTop,scrollL=elem.scrollLeft,height=elem.offsetHeight,width=elem.offsetWidth,startY=e.touches[0].pageY,startX=e.touches[0].pageX,scrollHeight=elem.scrollHeight,scrollWidth=elem.scrollWidth,move=function(e){var ty=scrollT+startY-e.touches[0].pageY,tx=scrollL+startX-e.touches[0].pageX,down=ty>=(lastTops.length?lastTops[0]:0),right=tx>=(lastLefts.length?lastLefts[0]:0);if((ty>0&&ty<scrollHeight-height)||(tx>0&&tx<scrollWidth-width)){e.preventDefault();}
else{changeScrollTarget(touchStartE);}
if(lastDown&&down!==lastDown){resetVertTracking();}
if(lastRight&&right!==lastRight){resetHorTracking();}
lastDown=down;lastRight=right;elem.scrollTop=ty;elem.scrollLeft=tx;lastTops.unshift(ty);lastLefts.unshift(tx);if(lastTops.length>3){lastTops.pop();}
if(lastLefts.length>3){lastLefts.pop();}},end=function(e){setPointers("auto");setTimeout(function(){setPointers("none");},450);elem.removeEventListener("touchmove",move,false);elem.removeEventListener("touchend",end,false);};elem.addEventListener("touchmove",move,false);elem.addEventListener("touchend",end,false);};doc.addEventListener("touchstart",start,false);};})(this,this.overthrow);